In [5]:
from tensorflow.keras.preprocessing.text import one_hot

In [6]:
## sentences
sent = [
    'the glass of milk',
    'the glass of juice',
    'the cup of tea',
    'I am a good boy',
    'I am a good developer',
    'I love learning Python',
    'Python is easy to learn',
    'I am learning machine learning',
    'I am learning deep learning',
    'I understand the meaning of words',
    'I enjoy working with data',
    'Data science is interesting',
    'Artificial intelligence is powerful',
    'Your videos are good'
]

In [7]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'I love learning Python',
 'Python is easy to learn',
 'I am learning machine learning',
 'I am learning deep learning',
 'I understand the meaning of words',
 'I enjoy working with data',
 'Data science is interesting',
 'Artificial intelligence is powerful',
 'Your videos are good']

In [8]:
## define the vocabulary size
voc_size = 10000

In [10]:
## one hot representation of the sentences
one_hot_repr=[one_hot(words, voc_size) for words in sent]
one_hot_repr
## here you can see that each word is represented a unique index number. The index number is generated based on the hash function. The same word will always have the same index number.

[[2376, 3035, 1763, 7562],
 [2376, 3035, 1763, 4257],
 [2376, 3191, 1763, 1989],
 [5907, 884, 8219, 2473, 5418],
 [5907, 884, 8219, 2473, 5762],
 [5907, 1471, 8417, 8433],
 [8433, 378, 2821, 1925, 9939],
 [5907, 884, 8417, 9141, 8417],
 [5907, 884, 8417, 2467, 8417],
 [5907, 5972, 2376, 1756, 1763, 7473],
 [5907, 4812, 3780, 5860, 3011],
 [3011, 6498, 378, 5761],
 [4850, 3633, 378, 1043],
 [5597, 9713, 9302, 2473]]

In [ ]:
## word embedding representation
from tensorflow.keras.layers import Embedding
from tensorflow.keras.utils import pad_sequences ## see all sentences are not of same lenth some are of 4 words and some are of 5 words. So we need to make all sentences of same length. For that we will use pad_sequences function.pad_sequences add zeros from front or back of the sentence to make all sentences of same length. By default it adds zeros from front of the sentence.
from tensorflow.keras.models import Sequential
import numpy as np

In [13]:
sent_length = 8
embedded_docs = pad_sequences(one_hot_repr, padding='pre', maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 2376 3035 1763 7562]
 [   0    0    0    0 2376 3035 1763 4257]
 [   0    0    0    0 2376 3191 1763 1989]
 [   0    0    0 5907  884 8219 2473 5418]
 [   0    0    0 5907  884 8219 2473 5762]
 [   0    0    0    0 5907 1471 8417 8433]
 [   0    0    0 8433  378 2821 1925 9939]
 [   0    0    0 5907  884 8417 9141 8417]
 [   0    0    0 5907  884 8417 2467 8417]
 [   0    0 5907 5972 2376 1756 1763 7473]
 [   0    0    0 5907 4812 3780 5860 3011]
 [   0    0    0    0 3011 6498  378 5761]
 [   0    0    0    0 4850 3633  378 1043]
 [   0    0    0    0 5597 9713 9302 2473]]


In [14]:
## feature representation of the sentences
dim =10

In [15]:
model = Sequential()
model.add(Embedding(voc_size, dim, input_length=sent_length))
model.compile('adam', 'mse')

c:\Users\harsh\anaconda3\Lib\site-packages\keras\src\layers\core\embedding.py:123: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [16]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [17]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 236ms/step


array([[[ 0.02234227, -0.03271081, -0.009033  , ...,  0.03407973,
          0.03706883,  0.04128324],
        [ 0.02234227, -0.03271081, -0.009033  , ...,  0.03407973,
          0.03706883,  0.04128324],
        [ 0.02234227, -0.03271081, -0.009033  , ...,  0.03407973,
          0.03706883,  0.04128324],
        ...,
        [ 0.01949731,  0.00141738,  0.03071293, ..., -0.0039679 ,
         -0.04927874, -0.02053038],
        [ 0.00824623,  0.04547906, -0.01379416, ...,  0.00412552,
         -0.02777978, -0.02267103],
        [ 0.00698451,  0.01502471,  0.0047466 , ...,  0.01398141,
          0.02334323,  0.02303667]],

       [[ 0.02234227, -0.03271081, -0.009033  , ...,  0.03407973,
          0.03706883,  0.04128324],
        [ 0.02234227, -0.03271081, -0.009033  , ...,  0.03407973,
          0.03706883,  0.04128324],
        [ 0.02234227, -0.03271081, -0.009033  , ...,  0.03407973,
          0.03706883,  0.04128324],
        ...,
        [ 0.01949731,  0.00141738,  0.03071293, ..., -

In [18]:
embedded_docs[0]

array([   0,    0,    0,    0, 2376, 3035, 1763, 7562], dtype=int32)